
services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
        .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d oficina_db"]
      interval: 5s
      retries: 5

  oficinatech.api:
    image: ${DOCKER_REGISTRY-}oficinatechapi
    build:
      context: .
      dockerfile: src/OficinaTech.API/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: ${DATABASE_URL}
    ports:
      - "8080:80"

volumes:
  postgres_data:
